# compiler we are using
CC = gcc

# adding compilere flags
CFLAGS =  -g -Wall

# the build target: 
TARGET = ${EXE}

all: ${TARGET}

${TARGET}: ${TARGET}.c ; ${CC} ${CFLAGS} -o ${TARGET} ${TARGET}.c ${LFLAGS}